services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux:latest
  - docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=P@ssw0rd1' -h mydb -p 1433:1433 --name mssqldb -d microsoft/mssql-server-linux
  - sleep 90
  - docker exec -t mssqldb /opt/mssql-tools/bin/sqlcmd -S mydb -U SA -P 'P@ssw0rd1' -Q "CREATE DATABASE rsqlserverdb;"

install:
  - docker build -t rsqlserver .

script:
  - docker run --link=mssqldb rsqlserver Rscript -e 'devtools::check(document = FALSE, check_dir = ".", cleanup = FALSE)'
  - grep -q -R "ERROR" /usr/local/R/rsqlserver.Rcheck/00check.log
  - exit $?
