services:
  - docker

before_install:
  - docker network create sqlserver_net

install:
  - docker build -t rsqlserver -f .ci/Dockerfile .

script:
  - printenv | grep -E '^TRAVIS' | sed 's/^/-e /' | xargs
  - |
    docker run -e CI=true -e CONTINUOUS_INTEGRATION=true "$(printenv | grep -E '^TRAVIS' | sed 's/^/-e /' | xargs)" \
      -t --network sqlserver_net --name pkgcheck rsqlserver Rscript \
        -e 'identical(Sys.getenv("TRAVIS"), "true")' \
        -e 'print(Sys.getenv("TRAVIS"))' \
        -e 'print(Sys.getenv("CI"))' \
        -e 'print(Sys.getenv("TRAVIS_COMMIT"))'
  - exit 0
